services:
  backend:
    container_name: llmanipulate-backend
    restart: unless-stopped
    build:
      context: llmanipulate-backend
    env_file: backend.env

  frontend:
    container_name: llmanipulate-frontend
    restart: unless-stopped
    build:
      context: llmanipulate-frontend
    env_file: frontend.env

  database: # https://hub.docker.com/_/postgres
    container_name: llmanipulate-db
    image: postgres:alpine
    restart: always
    shm_size: 128mb
    env_file: backend.env

  server:
    container_name: llmanipulate-server
    image: caddy:alpine
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/caddy_data:/data
      - ./caddy/caddy_config:/config
